apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace 'com.behi.zoha'
    compileSdk 30
    buildToolsVersion '30.0.2'

    defaultConfig {
        applicationId 'com.behi.zoha'
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 2
        versionName '1.1'
    }

    signingConfigs {
        release {
            storeFile file("../" + (keystoreProperties['storeFile'] ?: "release.keystore"))
            storePassword keystoreProperties['storePassword'] ?: "zoha1234"
            keyAlias keystoreProperties['keyAlias'] ?: "zoha-release"
            keyPassword keystoreProperties['keyPassword'] ?: "zoha1234"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.3.1'
    implementation 'com.google.android.material:material:1.3.0'

    implementation 'com.google.android.gms:play-services-auth:20.0.0'

    implementation 'com.github.bumptech.glide:glide:4.16.0'

    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.okhttp3:okhttp:4.9.3'

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
}
